export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT'
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING'
};

export const USER_PERMISSIONS = {
  // User Management
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // Profile Management
  MANAGE_PROFILES: 'MANAGE_PROFILES',
  VIEW_PROFILES: 'VIEW_PROFILES',
  UPDATE_PROFILE: 'UPDATE_PROFILE',

  // Role Management
  MANAGE_ROLES: 'MANAGE_ROLES',
  ASSIGN_ROLES: 'ASSIGN_ROLES',

  // System Settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_SETTINGS: 'VIEW_SETTINGS'
};

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: Object.values(USER_PERMISSIONS),
  [USER_ROLES.SCHOOL_ADMIN]: [
    USER_PERMISSIONS.VIEW_USERS,
    USER_PERMISSIONS.CREATE_USER,
    USER_PERMISSIONS.UPDATE_USER,
    USER_PERMISSIONS.VIEW_PROFILES,
    USER_PERMISSIONS.UPDATE_PROFILE,
    USER_PERMISSIONS.VIEW_SETTINGS
  ],
  [USER_ROLES.TEACHER]: [
    USER_PERMISSIONS.VIEW_PROFILES,
    USER_PERMISSIONS.UPDATE_PROFILE
  ],
  [USER_ROLES.STUDENT]: [
    USER_PERMISSIONS.VIEW_PROFILES,
    USER_PERMISSIONS.UPDATE_PROFILE
  ],
  [USER_ROLES.PARENT]: [
    USER_PERMISSIONS.VIEW_PROFILES,
    USER_PERMISSIONS.UPDATE_PROFILE
  ]
};

export const GENDER_OPTIONS = [
  { value: 'MALE', label: 'Male' },
  { value: 'FEMALE', label: 'Female' },
  { value: 'OTHER', label: 'Other' }
];

export const PASSWORD_REQUIREMENTS = {
  minLength: 8,
  requireUppercase: true,
  requireLowercase: true,
  requireNumbers: true,
  requireSpecialChars: true
};
