export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
};

export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_CLASSES: 'MANAGE_CLASSES',
  VIEW_CLASSES: 'VIEW_CLASSES',
  MANAGE_SUBJECTS: 'MANAGE_SUBJECTS',
  MANAGE_ATTENDANCE: 'MANAGE_ATTENDANCE',
  VIEW_ATTENDANCE: 'VIEW_ATTENDANCE',
  MANAGE_EXAMS: 'MANAGE_EXAMS',
  VIEW_EXAMS: 'VIEW_EXAMS',
  MANAGE_FEES: 'MANAGE_FEES',
  VIEW_FEES: 'VIEW_FEES',
  MANAGE_LEAVE: 'MANAGE_LEAVE',
  VIEW_LEAVE: 'VIEW_LEAVE',
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.MANAGE_SUBJECTS,
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.MANAGE_FEES,
    PERMISSIONS.MANAGE_LEAVE,
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.VIEW_LEAVE,
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_LEAVE,
  ],
  [ROLES.PARENT]: [
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.VIEW_FEES,
  ],
}; 