export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
};

export const PERMISSIONS = {
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  // Add more permissions as needed
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.VIEW_USERS,
  ],
  [ROLES.TEACHER]: [PERMISSIONS.VIEW_USERS],
  [ROLES.STUDENT]: [],
  [ROLES.PARENT]: [],
}; 